Function/unload
savoirfairelinux/vanilla-slick pull request #30
Opened 2016-09-28 15:31 UTC by pieplu

#22

2016-09-28 16:34 UTC, amtur8 requested changes
Côté fonctionnel, tout fonctionne.

2016-09-28 16:34 UTC, amtur8 commented on slick/slick.js
> +			_.removeNodeUtil(_.$dots.get(0));
Je ramènerais tous les .get() et .get(0) en début de fonction. Ça va être plus facile de vanillifier ceci lorsqu'on va être rendu là.

2016-10-07 21:01 UTC, pieplu commented on slick/slick.js
> +			_.removeNodeUtil(_.$dots.get(0));
Done @amtur8

2016-10-13 19:22 UTC, amtur8 commented on slick/slick.js
> +			_.d_$dots = _.$dots ? _.$dots.get(0) : false,
@pieplu j'ai un blanc... est-ce que $dots est une collection de Nodes ou un seul élément qui contient tous les dots ?

2016-10-13 19:26 UTC, hs0ucy commented on slick/slick.js
> +			_.d_$dots = _.$dots ? _.$dots.get(0) : false,
@amtur8 `_.$dots`, c'est le UL non?

2016-10-13 21:09 UTC, pieplu commented on slick/slick.js
> +			_.d_$dots = _.$dots ? _.$dots.get(0) : false,
Yep @amtur8 @hs0ucy dots est bien une `ul` :)

2016-10-13 21:10 UTC, pieplu commented on slick/slick.js
> +			_.d_$dots = _.$dots ? _.$dots.get(0) : false,
do I have to use the new convention, with `$$` ?

2016-10-14 14:26 UTC, hs0ucy commented on slick/slick.js
> +			_.d_$dots = _.$dots ? _.$dots.get(0) : false,
@pieplu I proposed `_$$`, but i don't mind if it's an other kind of prefix...
/cc @amtur8 @Tonours @ubik23

2016-10-14 15:11 UTC, amtur8 approved these changes

2016-10-14 15:31 UTC, pieplu commented
Convention updated! @amtur8 @hs0ucy I think you can merge!

2016-10-14 15:37 UTC, amtur8 requested changes
J'aime beaucoup la meilleure lisibilité du code suite à ce changement :)

2016-10-14 15:37 UTC, amtur8 commented on slick/slick.js
> +		var _ = this
rajoute un `;` et ajuste l'indentation des lignes du dessous :)

2016-10-14 15:43 UTC, pieplu commented on slick/slick.js
> +		var _ = this
-_- ... Done ^^

2016-10-14 15:51 UTC, amtur8 approved these changes

2016-10-14 15:53 UTC, merged